paths:
  /studies/{id}/clone:
    put:
      operationId: saveStudyAs
      parameters:
        - in: path
          name: id
          required: true
          description: Study id
          type: integer
        - name: name
          in: query
          required: true
          description: Study name
          type: string
      responses:
        "200":
          description: Ok
          schema:
            $ref: "#/definitions/Study"
        "500":
          description: Not ok
          schema:
            $ref: "#/definitions/Error"
  /lines/{id}/getListLine:
    get:
      operationId: loadPipeline
      parameters:
        - name: id
          in: path
          require: true
          type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewLineList"
  /lines/saveLines:
    post:
      operationId: savePipelines
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/CreateModiPipeLine"
          description: create a new pipe line!!
      responses:
        "200":
          description: OK
        "500":
          description: Can not created!
          schema:
            $ref: "#/definitions/Error"
  /reports/{id}/downLoadPDF:
    post:
      operationId: downLoadPDF
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - name: reportParam
          in: body
          required: true
          schema:
            $ref: "#/definitions/Report"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewResponseUrl"
        "500":
          description: Can not download PDF!
          schema:
            $ref: "#/definitions/Error"
  /reports/{id}/downLoadHtmlToPDF:
    post:
      operationId: downLoadHtmlToPDF
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - name: reportParam
          in: body
          required: true
          schema:
            $ref: "#/definitions/Report"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewResponseUrl"
        "500":
          description: Can not download PDF!
          schema:
            $ref: "#/definitions/Error"
  /reports/{id}/processingReport:
    get:
      operationId: processingReport
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewProcessingReport"
        "500":
          description: Processing failed!
          schema:
            $ref: "#/definitions/Error"
