paths:
  /referencedata/packing:
    get:
      operationId: findRefPackingElmt
      tags:
      - referencedata
      description: Get a list of packingelmt
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewPackingElmt"
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: updatePacking
      tags:
      - referencedata
      description: update packing
      parameters:
      - name: body
        in: body
        required: true
        description: body update packing
        schema:
          $ref: "#/definitions/PackingElmt"
      responses:
        "200":
          description: ok
          schema:
            $ref: "#/definitions/PackingElmt"
        "422":
          description: missing data
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: newPacking
      tags:
      - referencedata
      description: Create new packing
      parameters:
      - name: body
        in: body
        required: true
        description: body create new packing
        schema:
          $ref: "#/definitions/PackingElmt"
      responses:
        "200":
          description: ok
          schema:
            $ref: "#/definitions/PackingElmt"
        "422":
          description: missing data
  /referencedata/packing/{id}:
    delete:
      operationId: deletePacking
      tags:
      - referencedata
      description: delete Packing
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: packing delete successfully
          schema:
            type: integer
  /referencedata/packingelmt:
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: saveAsPacking
      tags:
      - referencedata
      description: save as packing
      parameters:
      - name: body
        in: body
        required: true
        description: body save as packing
        schema:
          $ref: "#/definitions/PackingElmt"
      responses:
        "200":
          description: ok
          schema:
            $ref: "#/definitions/PackingElmt"
        "422":
          description: missing data
  /referencedata/pipeline:
    get:
      operationId: findRefPipeline
      tags:
      - referencedata
      description: Get a list of pipeLineElmt
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewPipeLineElmt"
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: newPipeLine
      tags:
      - referencedata
      description: Create new pipeline
      parameters:
      - name: body
        in: body
        required: true
        description: body create new pipeline
        schema:
          $ref: "#/definitions/PipeLineElmt"
      responses:
        "200":
          description: ok
          schema:
            $ref: "#/definitions/PipeLineElmt"
        "422":
          description: missing data
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: updatePipeLine
      tags:
      - referencedata
      description: update pipe line
      parameters:
      - name: body
        in: body
        required: true
        description: body update pipe line
        schema:
          $ref: "#/definitions/PipeLineElmt"
      responses:
        "200":
          description: ok
          schema:
            $ref: "#/definitions/PipeLineElmt"
        "422":
          description: missing data
  /referencedata/pipeline/{id}:
    delete:
      operationId: deletePipeLine
      tags:
      - referencedata
      description: delete pipe line
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: pipe line delete successfully
          schema:
              type: integer
  /referencedata/lineelmt:
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: saveAsPipeLine
      tags:
      - referencedata
      description: save as pipe line
      parameters:
      - name: body
        in: body
        required: true
        description: body save as pipe line
        schema:
          $ref: "#/definitions/PipeLineElmt"
      responses:
        "200":
          description: ok
          schema:
            $ref: "#/definitions/PipeLineElmt"
        "422":
          description: missing data
  /translation/linetype:
    get:
      operationId: getListLineType
      description: Get list line type
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Translation"
  /translation/energies:
    get:
      operationId: getListEnergies
      description: Get list energies (list cooling family)
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Translation"
  /referencedata/equipments:
    get:
      operationId: findRefEquipment
      tags:
      - referencedata
      description: Get a list of equipment
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewEquipment"
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: newEquipment
      tags:
      - referencedata
      description: Create new equipment
      parameters:
      - name: body
        in: body
        required: true
        description: body create new equipment
        schema:
          $ref: "#/definitions/NewEquipment"
      responses:
        "200":
          description: ok
          schema:
            $ref: "#/definitions/RefEquipment"
        "422":
          description: missing data
  /referencedata/equipment:
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: saveAsEquipment
      tags:
      - referencedata
      description: save as equipment
      parameters:
      - name: body
        in: body
        required: true
        description: body create new equipment
        schema:
          $ref: "#/definitions/SaveAsEquipment"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: saveEquipment
      tags:
      - referencedata
      description: save equipment
      parameters:
      - name: body
        in: body
        required: true
        description: body save equipment
        schema:
          $ref: "#/definitions/SaveEquipment"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
  /referencedata/equipmentfamilys:
    get:
      operationId: getEquipmentFamily
      tags:
        - referencedata
      description: Get a list of equipment family
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/EquipmentFamily"
  /referencedata/equipmentseries:
    get:
      operationId: getEquipmentSeries
      tags:
        - referencedata
      description: Get list equipment series
      parameters:
        - name: idFamily
          in: query
          required: true
          description: ID equipment family
          type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/EquipmentSeries"
  /referencedata/ramps:
    get:
      operationId: getRamps
      tags:
        - referencedata
      description: Get list Ramps
      parameters:
        - name: idEquip
          in: query
          required: true
          description: ID equipment
          type: integer
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Ramps"
  /referencedata/shelves:
    get:
      operationId: getShelves
      tags:
        - referencedata
      description: Get list Shelves
      parameters:
        - name: idEquip
          in: query
          required: true
          description: ID equipment
          type: integer
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Shelves"
  /referencedata/consumptions:
    get:
      operationId: getConsumptions
      tags:
        - referencedata
      description: Get list Consumptions
      parameters:
        - name: idEquip
          in: query
          required: true
          description: ID equipment
          type: integer
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Consumptions"
  /referencedata/equipment/{id}:
    delete:
      operationId: deleteEquipment
      tags:
      - referencedata
      description: delete equipment
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: delete equipment successfully
          schema:
              type: integer
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: startEquipmentCalculate
      tags:
      - referencedata
      description: run equipment calculate
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "422":
          description: missing data
  /referencedata/equipcharacts/{idEquip}:
    get:
      operationId: getEquipmentCharacts
      tags:
      - referencedata
      parameters:
      - name: idEquip
        in: path
        description: equipment id
        type: integer
      description: Get list equipment chart by Id equipment
      responses:
        "200":
          description: Successful retrieve the equipment chart
          schema:
            type: array
            items:
              $ref: "#/definitions/EquipCharact"
    delete:
      operationId: deleteEquipCharacts
      tags:
      - referencedata
      description: delete list equip charact
      parameters:
      - name: idEquip
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: delete list equipcharact successfully
          schema:
              type: integer
  /referencedata/highchart:
    get:
      operationId: getDataHighChart
      tags:
      - referencedata
      parameters:
      - name: ID_EQUIP
        in: query
        required: true
        type: integer
      - name: profilType
        in: query
        required: true
        type: number
      - name: profilFace
        in: query
        required: true
        type: number
      - name: minScaleY
        in: query
        required: true
        type: number
      - name: maxScaleY
        in: query
        required: true
        type: number
      - name: typeChart
        in: query
        required: true
        type: integer
      - name: newProfil
        in: query
        required: true
        type: string
      description: Get data highchart
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewHighChart"
    post:
      consumes:
        - application/x-www-form-urlencoded
      operationId: saveSelectedProfile
      description: save Selected Profile
      tags:
      - referencedata
      parameters:
      - name: body
        in: body
        required: true
        description: body save DataHightChart
        schema:
          $ref: "#/definitions/DataHightChart"
      responses:
        "200":
          description: OK
          schema:
            type: integer

  /referencedata/equipcharact/{id}:
    get:
      operationId: getEquipCharactById
      tags:
      - referencedata
      parameters:
      - name: id
        in: path
        description: Compenth id
        type: integer
      description: Get equipcharact by id
      responses:
        "200":
          description: Successful retrieve the equipcharact
          schema:
              $ref: "#/definitions/EquipCharact"
    delete:
      operationId: deleteEquipCharact
      tags:
      - referencedata
      description: delete equip charact
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: delete equipcharact successfully
          schema:
              type: integer
  /referencedata/equipcharact:
    put:
      operationId: updateEquipCharact
      tags:
      - referencedata
      parameters:
      - name: body
        in: body
        required: true
        description: update equip EquipCharact
        schema:
          $ref: "#/definitions/EquipCharact"
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "422":
          description: missing data
    post:
      operationId: addEquipCharact
      tags:
      - referencedata
      parameters:
      - name: body
        in: body
        required: true
        description: add equip EquipCharact
        schema:
          $ref: "#/definitions/EquipCharact"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/EquipCharact"
        "422":
          description: missing data
  /referencedata/curve/{idEquip}:
    get:
      operationId: getDataCurve
      tags:
      - referencedata
      parameters:
      - name: idEquip
        in: path
        required: true
        type: number
      description: Get data curve
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewCurve"
  /referencedata/redrawcurves:
    put:
      operationId: redrawCurves
      tags:
      - referencedata
      parameters:
      - name: body
        in: body
        required: true
        description: redrawCurves
        schema:
          $ref: "#/definitions/ViewCurve"
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "422":
          description: missing data
  /referencedata/tempsetpoint/{idEquip}:
    get:
      operationId: getTempSetPoint
      tags:
      - referencedata
      parameters:
      - name: idEquip
        in: path
        description: equipment id
        type: integer
      description: Get set temp point
      responses:
        "200":
          description: Successful retrieve the tem set point
          schema:
              $ref: "#/definitions/ViewTempSetPoint"
  /referencedata/tempsetpoint:
    put:
      operationId: buildForNewTR
      tags:
      - referencedata
      parameters:
      - name: body
        in: body
        required: true
        description: build for new TR
        schema:
          $ref: "#/definitions/ViewTempSetPoint"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ResultBuildForNewTR"
        "422":
          description: missing data
  /referencedata/capability/{idEquip}:
    get:
      operationId: getCapabitity
      tags:
      - referencedata
      parameters:
      - name: idEquip
        in: path
        description: equipment id
        type: integer
      description: Get value capability
      responses:
        "200":
          description: Successful capability
          schema:
              $ref: "#/definitions/ViewCapability"
