paths:
  /referencedata/packing:
    get:
      operationId: findRefPackingElmt
      tags:
      - referencedata
      description: Get a list of packingelmt
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewPackingElmt"
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: newPacking
      tags:
      - referencedata
      description: Create new packing
      parameters:
      - name: body
        in: body
        required: true
        description: body create new packing
        schema:
          $ref: "#/definitions/NewPacking"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
  /referencedata/packing/{id}:
    delete:
      operationId: deletePacking
      tags:
      - referencedata
      description: delete Packing
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: packing delete successfully
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: updatePacking
      tags:
      - referencedata
      description: update packing
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - name: body
        in: body
        required: true
        description: body update packing
        schema:
          $ref: "#/definitions/NewPacking"
      responses:
        "200":
          description: ok
          schema:
            type: array
            items:
              type: integer
        "422":
          description: missing data
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: saveAsPacking
      tags:
      - referencedata
      description: save as packing
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - name: body
        in: body
        required: true
        description: body save as packing
        schema:
          $ref: "#/definitions/NewPacking"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
  /referencedata/pipeline:
    get:
      operationId: findRefPipeline
      tags:
      - referencedata
      description: Get a list of pipeLineElmt
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewPipeLineElmt"
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: newPipeLine
      tags:
      - referencedata
      description: Create new pipeline
      parameters:
      - name: body
        in: body
        required: true
        description: body create new pipeline
        schema:
          $ref: "#/definitions/PipeLineElmt"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
  /referencedata/pipeline/{id}:
    delete:
      operationId: deletePipeLine
      tags:
      - referencedata
      description: delete pipe line
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: pipe line delete successfully
          schema:
              type: integer
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: updatePipeLine
      tags:
      - referencedata
      description: update pipe line
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - name: body
        in: body
        required: true
        description: body update pipe line
        schema:
          $ref: "#/definitions/PipeLineElmt"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: saveAsPipeLine
      tags:
      - referencedata
      description: save as pipe line
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      - name: name
        in: query
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
  /translation/linetype:
    get:
      operationId: getListLineType
      description: Get list line type
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Translation"
  /translation/energies:
    get:
      operationId: getListEnergies
      description: Get list energies (list cooling family)
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/Translation"
  /referencedata/equipments:
    get:
      operationId: findRefEquipment
      tags:
      - referencedata
      description: Get a list of equipment
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/ViewEquipment"
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: newEquipment
      tags:
      - referencedata
      description: Create new equipment
      parameters:
      - name: body
        in: body
        required: true
        description: body create new equipment
        schema:
          $ref: "#/definitions/NewEquipment"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
  /referencedata/equipment:
    put:
      consumes:
      - application/x-www-form-urlencoded
      operationId: saveAsEquipment
      tags:
      - referencedata
      description: save as equipment
      parameters:
      - name: body
        in: body
        required: true
        description: body create new equipment
        schema:
          $ref: "#/definitions/SaveAsEquipment"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: saveEquipment
      tags:
      - referencedata
      description: save equipment
      parameters:
      - name: body
        in: body
        required: true
        description: body save equipment
        schema:
          $ref: "#/definitions/SaveEquipment"
      responses:
        "200":
          description: ok
          schema:
              type: integer
        "422":
          description: missing data
  /referencedata/equipmentfamilys:
    get:
      operationId: getEquipmentFamily
      tags:
        - referencedata
      description: Get a list of equipment family
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/EquipmentFamily"
  /referencedata/equipmentseries:
    get:
      operationId: getEquipmentSeries
      tags:
        - referencedata
      description: Get list equipment series
      parameters:
        - name: idFamily
          in: query
          required: true
          description: ID equipment family
          type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/EquipmentSeries"
  /referencedata/ramps:
    get:
      operationId: getRamps
      tags:
        - referencedata
      description: Get list Ramps
      parameters:
        - name: idEquip
          in: query
          required: true
          description: ID equipment
          type: integer
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Ramps"
  /referencedata/shelves:
    get:
      operationId: getShelves
      tags:
        - referencedata
      description: Get list Shelves
      parameters:
        - name: idEquip
          in: query
          required: true
          description: ID equipment
          type: integer
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Shelves"
  /referencedata/consumptions:
    get:
      operationId: getConsumptions
      tags:
        - referencedata
      description: Get list Consumptions
      parameters:
        - name: idEquip
          in: query
          required: true
          description: ID equipment
          type: integer
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Consumptions"
  /referencedata/equipment/{id}:
    delete:
      operationId: deleteEquipment
      tags:
      - referencedata
      description: delete equipment
      parameters:
      - name: id
        in: path
        required: true
        type: integer
      responses:
        "200":
          description: delete equipment successfully
          schema:
              type: integer
